repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--strict, --explicit-package-bases]
        additional_dependencies:
          - aiogram>=3
          - sqlalchemy[asyncio]>=2
          - alembic>=1
          - aiogram-dialog>=2
          - pydantic>=2
          - pydantic-settings>=2
          - loguru>=0.7
          - faker>=38
